# Generated by Django 2.2.5 on 2019-10-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_auto_20191009_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
