# Generated by Django 2.2.5 on 2019-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_delete_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='key',
            field=models.TextField(default=1, max_length=282),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserKey',
        ),
    ]
